logging.level.org.zalando.logbook= TRACE 
spring.sql.init.mode=always
# ? jdbc-url ??????? ???? ? ????? ???? ??????
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
spring.datasource.url=jdbc:h2:file:./db/filmorate
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password