
CREATE TABLE IF NOT EXISTS film_genres (
    id INTEGER PRIMARY KEY,
    name varchar(40) NOT NULL,
    CONSTRAINT uq_film_genres_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS film_ratings (
    id INTEGER PRIMARY KEY,
    name varchar(40) NOT NULL,
    CONSTRAINT uq_film_rating_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(40) NOT NULL,
    login varchar(40) NOT NULL,
    user_name varchar(50) NOT NULL,
    birthday DATE NOT NULL,

    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_login UNIQUE (login)
);

CREATE TABLE IF NOT EXISTS user_relation_statuses (
    id INTEGER PRIMARY KEY,
    name varchar(20) NOT NULL,
    CONSTRAINT uq_status_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL,
    description varchar(200) NOT NULL,
    realise_date DATE NOT NULL,
    duration INTEGER NOT NULL,
    rating_id INTEGER,

    CONSTRAINT films_rating_id
        FOREIGN KEY (rating_id) REFERENCES film_ratings(id)

);

CREATE TABLE IF NOT EXISTS film_genre_binding (
    film_id  INTEGER NOT NULL,
    genre_id INTEGER NOT NULL,
    PRIMARY KEY (film_id, genre_id),

    CONSTRAINT films_genre_id_ref
        FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,

    CONSTRAINT genre_dictionary_id
        FOREIGN KEY (genre_id) REFERENCES film_genres(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users_liked_film (
    film_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,

    CONSTRAINT pk_users_liked_film PRIMARY KEY (film_id, user_id),

    CONSTRAINT film_id_key
        FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,

    CONSTRAINT user_id_key
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_relations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id INTEGER NOT NULL,
    addressee_id INTEGER NOT NULL,

    CONSTRAINT fk_user_relations_user
        FOREIGN KEY (requester_id) REFERENCES users(id) ON DELETE CASCADE,

    CONSTRAINT another_user_relations_user
        FOREIGN KEY (addressee_id) REFERENCES users(id) ON DELETE CASCADE,

    CONSTRAINT chk_user_not_self
        CHECK (requester_id <> addressee_id),

    CONSTRAINT uq_user_relation UNIQUE (requester_id, addressee_id)
);







